version: '2.4'
services:
    cabernet:
        container_name: cabernet
        image: ghcr.io/cabernetwork/cabernet:latest
        environment:
          - TZ="Etc/UTC"  # Timezone (Optional)
          - PUID=1000     # UserID (Optional)
          - PGID=1000     # GroupID (Optional)
        ports:
          - "6077:6077"    # Web Interface Port
          - "5004:5004"    # Port used to stream
        restart: unless-stopped
        volumes:
          - /path/to/cabernet/data:/app/data                # App data (Optional)
          - /path/to/cabernet/plugins_ext:/app/plugins_ext  # Plugins Data (Optional)
          - /path/to/cabernet/secrets:/app/.cabernet        # Ecryption key data (Optional)
